version: '3'
services:
  ue2:
    image: kikikiky/ueransim:2.0.0
    container_name: ue2
    command: 
      - ue
    cap_add:
      - all
    privileged: true
    environment:
      GNB_HOSTNAME: gnb1
      APN: internet.lgep5g.net
      MSISDN: '0000054041'
      KEY: '30AA8C743C9F258E6DEB2665E2785231'
      OP_TYPE: OPC
      OP: 'DB008E32D942D562109C0C59C4B35E2D'
      MCC: '999'
      MNC: '70'
      SST: '1'
      SD: '1'
      GNB_ADDR: '10.177.55.101'
    network_mode: "host"

  ue3:
    image: kikikiky/ueransim:2.0.0
    container_name: ue3
    command: 
      - ue
    cap_add:
      - all
    privileged: true
    environment:
      GNB_HOSTNAME: gnb1
      APN: internet.lgep5g.net
      MSISDN: '0000054042'
      KEY: 'BEACBF86E61B0E56F87DAFEC84CBACE3'
      OP_TYPE: OPC
      OP: 'B1B14D77DA20DC8E3181DACFBA04A964'
      MCC: '999'
      MNC: '70'
      SST: '1'
      SD: '1'
      GNB_ADDR: '10.177.55.101'
    network_mode: "host"
