version: '3'
services: 
  gnb1:
    image: kikikiky/ueransim:2.0.0
    container_name: gnb1
    command: 
      - gnb
    cap_add:
      - all
    privileged: true
    environment:
      AMF_HOSTNAME: amf
      GNB_HOSTNAME: gnb1
      MCC: '001'
      MNC: '01'
      SST: '1'
      SD: '1'
      GNB_ADDR: '10.177.55.100'
      AMF_ADDR: '10.177.55.102'
    network_mode: "host"
      
  ue1:
    image: kikikiky/ueransim:2.0.0
    container_name: ue1
    command: 
      - ue
    cap_add:
      - all
    privileged: true
    environment:
      GNB_HOSTNAME: gnb1
      APN: internet
      MSISDN: '0000000001'
      KEY: '465B5CE8B199B49FAA5F0A2EE238A6BC'
      OP_TYPE: OPC
      OP: 'E8ED289DEBA952E4283B54E88E6183CA'
      MCC: '001'
      MNC: '01'
      SST: '1'
      SD: '1'
      GNB_ADDR: '10.177.55.100'
    network_mode: "host"

