FROM debian:buster-slim as builder

ARG version=2.3.3
ENV VERSION=$version

LABEL org.opencontainers.image.authors="Yocheol Kim <yocheol.kim@lge.com>" \
      org.opencontainers.image.vendor="lge" \
      org.opencontainers.image.licenses="GNU AGPL v3.0" \
      org.opencontainers.image.version="$version"

RUN apt-get update && \
    apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
        python3-pip \
        python3-setuptools \
        python3-wheel \
        ninja-build \
        build-essential \
        flex \
        bison \
        git \
        meson \
        libsctp-dev \
        libgnutls28-dev \
        libgcrypt-dev \
        libssl-dev \
        libidn11-dev \
        libmongoc-dev \
        libbson-dev \
        libyaml-dev \
        iproute2 \
        ca-certificates \
        netbase \
        pkg-config \
        cmake \
        libnghttp2-dev \
        libmicrohttpd-dev \
        libcurl4-openssl-dev \
        libtins-dev \
        libtalloc-dev \
        wget && \
    apt-get clean
	
RUN apt-get update && apt-get install -y net-tools iputils-ping iproute2 dnsutils gettext-base iptables vim && \
    echo "alias ll='ls -al --color=auto'" >> ~/.bashrc
