FROM ubuntu:focal

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libsctp-dev \
        lksctp-tools \
        iproute2 \
        iptables \
        netbase \
        ifupdown \
        net-tools \
        curl \
        vim \
        gettext \
        host \
        traceroute \
        tcpdump \
        iputils-ping && \
    apt-get autoremove -y && apt-get autoclean && \
    echo "alias ll='ls -al --color=auto'" >> ~/.bashrc
    
COPY source/UERANSIM/build/* /usr/local/bin/

COPY ueransim_configs/ /etc/ueransim
COPY entrypoint_ueransim.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
#RUN apt-get install -y procps

ENV ENB_ID=0x19B \
    MCC=999 \
    MNC=70 \
    NETWORK=openverso.org \
    TAC=0001 \
    MSISDN=0000054040 \
    KEY=8EF27480B81B1C554E1194E0270AC876 \
    OP_TYPE=OPC \
    OP=47F63BA250652F1BE5DCA8C81DF145EB \
    SST=1 \
    SD=1 \
    UE_HOSTNAME=ue \
    GNB_HOSTNAME=gnb \
    AMF_HOSTNAME=amf \
    APN=internet.lgep5g.net

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/sh"]
